### PR TITLE
Moving package metadata to const

### PR DESCRIPTION
**Pull request by castaneai**
I was interested in this project and wrote a small code to make the TCP server work.
But I got the following error:

```
panic: [2019/03/13 09:18:41.549]<Core*>  FATAL - Failed to load package metadata: open /private/var/folders/lf/8yw389v949j1hzyy9h5zg54c0000gp/T/package.json
```

It looked like it was trying to reference the diarkis repository's package.json from my own project.
So I made two patches.

- Move the contents of package.json to const
- Change getting diarkispath ( `os.Args[0]` doesn't work when run through `go run` )

### CODE REVIEW

**Comment by voltrue2** [comment]
The change makes it so that it does not use package.json, would you please remove the file as well?

Cheers

**Comment by castaneai** [comment]
Oops, Snyk seems to treat package.json as a manifest.
Unfortunately, Gopkg is not currently supported by Snyk with GitHub. 😢
https://snyk.io/docs/snyk-for-golang/

**Comment by voltrue2** [comment]
Hmmm... need to do something about the manifest issue with snyk...
Thank you for the update on your PR though.

Cheers

**Comment by voltrue2** [comment]
@castaneai By the way, please make sure to run `make init` first so that you have git pre-commit hook setup to run golint and gomft. I missed it when I was reviewing the code, but the exported consts had no comments (this is illegal according to golint) and the spacing of the const was incorrect according to gofmt. 
Cheer!

**Comment by castaneai** [comment]
That make sense. I'll be careful from now on.

**Pull request merged**
